version: "3.9"

networks:
  fastapi_template:

services:
  fastapi:
    container_name: api
    build: 
      context: .
      dockerfile: ./docker/fastapi.dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/src:/app
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    networks:
      - fastapi_template

  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - fastapi_template-db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - fastapi_template

  nginx:
    container_name: nginx
    image: nginx:stable
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/${ENVIRONMENT}/conf:/etc/nginx/conf.d
    depends_on:
      - fastapi
      - frontend
    networks:
      - fastapi_template

  frontend:
    container_name: frontend
    build: 
        context: .
        dockerfile: ./docker/frontend.dockerfile
    env_file: .env
    volumes:
      - ./vue:/app
      - /app/node_modules
    networks:
      - fastapi_template

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - fastapi_template

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: ./docker/celery.dockerfile
    command: celery -A worker.worker worker --loglevel=info --concurrency=4
    env_file: .env
    volumes:
      - ./fastapi/src:/app
    depends_on:
      - rabbitmq
      - db
    networks:
      - fastapi_template

  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: ./docker/celery.dockerfile
    command: celery -A worker.worker beat
    env_file: .env
    volumes:
      - ./fastapi/src:/app
    depends_on:
      - rabbitmq
      - db
    networks:
      - fastapi_template

  flower:
    image: mher/flower:1.2.0
    container_name: flower
    env_file: .env
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - celery_worker
    networks:
      - fastapi_template

volumes:
  fastapi_template-db-data:
